### ISSUE TITLE
確診人數在圖表上分出境內或是境外

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/covid19#2]
## 改善詳細 / Details of Improvement
- 目前大多數是境外案例，不過從圖表上確實不容易看出來，如果可以看出來的話應該會比較好？

## 環境及瀏覽器 / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kelvin2go** [comment]
@PichuChen 我可以加

patients_summary > data 要加 境外/木土
```
patients_summary: {
date: {},
"data": { 
"境外": [], //item is daily count 
"本土":[]
},
labels:[] // "1/15.. date label"
}
```

**Comment by PichuChen** [comment]
感謝你，那我接下來會比照確診數字增加。

**Comment by PichuChen** [comment]
確認一下程式碼，如果不改Data格式的話他也會自動按照 patients 的 `境外或本土` 做判斷，所以不需要另外調整data格式
