### ISSUE TITLE
更新確診病例屬性的資料更新步驟

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/covid19#5]
## 改善詳細 / Details of Improvement
- 目前資料更新方式需要先在 Google Sheet 上新增資料
- 然後執行 curl 把 json 抓下來
- 接著再執行 `tw_g0v_google_sheet_json_to_pat_data.go` 這個 script 把檔案轉換成 data.json 中的格式
- 然後需要手動貼上更新 data.json

## 期待的行為 / Expected behavior
- 讓 `tw_g0v_google_sheet_json_to_pat_data.go` 可以直些在 data 資料夾中新增一份 patients.json
- 接著原先讀取 data.json 裡面的 patients 的程式修改為讀取  patients.json 

## 環境及瀏覽器 / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kelvin2go** [comment]
Does go support running script remote file ? I can run my script (thttps://github.com/kelvin2go/covid19-tw) with  tw_g0v_google_sheet_json_to_pat_data.go

**Comment by PichuChen** [comment]
目前主要的問題應該是要把data.json 拆分開來？

**Comment by kelvin2go** [comment]
直接生產兩條 json . 
covid19 就可直接讀 raw json ?

**Comment by PichuChen** [comment]
應該是這樣沒錯
