### ISSUE TITLE
在「確診案例概況」卡片中新增「案例編號」

### ISSUE THREAD

**Issue by PichuChen** [PichuChen/covid19#6]
由於在 PTT nCoV2019 上面有鄉民希望增加案例編號，同時有案例編號的話可以比較快確認這筆資料是哪個案例，所以提議新增案例編號。

請參考下面截圖，如果有更好的想法也歡迎提出，如果希望協助實作這個功能的話請回應「交給我」或是「Please assign to me」這樣我就會知道了

## 改善詳細 / Details of Improvement
- 需要修改的檔案應該是 `utils/formatTable.ts` 這份就行了

## 螢幕截圖 / Screenshot
原本的
![螢幕快照 0002-03-27 09 33 39](https://user-images.githubusercontent.com/600238/77713266-ead77d80-7010-11ea-9655-7e81b9d8c0b9.png)

改進後的 （參考）
![螢幕快照 0002-03-27 09 51 34](https://user-images.githubusercontent.com/600238/77713301-f7f46c80-7010-11ea-87c1-42663caf1b82.png)

## 期待的行為 / Expected behavior
- 多一欄案例編號

## 環境及瀏覽器 / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kelvin2go** [comment]
Please assign to me，i can do it

**Comment by PichuChen** [comment]
麻煩您了
